#Usando uma estrutura de repetição, crie um programa que imprima os valores dos n primeiros termos de uma sequência Fibonacci. Lembre-se que os números que compõem essa sequência são:0, 1,1,2,3,5,8,13,21,34...

